export const TAB_ITEMS = [
  {
    id: "following",
    title: "Following",
  },
  {
    id: "terminal",
    title: "Terminal",
  },
];
export const DEFAULT_TAB = TAB_ITEMS[1].id;
export const DUMMY_ITEMS = [
  {
    slug: "faposjflaksjdlf98932rjasjfkd1",
    imgUrl: "https://picsum.photos/128/128",
    name: "Lorem Ipsum Dolor Sit Amet",
    ticker: "LisDia",
    userName: "LOREMS",
    created: "2h ago",
    marketCap: 10000,
    replies: 77,
    text: "Lorem ipsum dolor lalala sit amet noto",
  },
  {
    slug: "faposjflaksjdlf98932rjasjfkd2",
    imgUrl: "https://picsum.photos/128/128",
    name: "Lorem Ipsum Dolor Sit Amet",
    ticker: "LisDia",
    userName: "LOREMS",
    created: "2h ago",
    marketCap: 10000,
    replies: 77,
    text: "Lorem ipsum dolor lalala sit amet noto",
  },
  {
    slug: "faposjflaksjdlf98932rjasjfkd3",
    imgUrl: "https://picsum.photos/128/128",
    name: "Lorem Ipsum Dolor Sit Amet",
    ticker: "LisDia",
    userName: "LOREMS",
    created: "2h ago",
    marketCap: 10000,
    replies: 77,
    text: "Lorem ipsum dolor lalala sit amet noto",
  },
  {
    slug: "faposjflaksjdlf98932rjasjfkd4",
    imgUrl: "https://picsum.photos/128/128",
    name: "Lorem Ipsum Dolor Sit Amet",
    ticker: "LisDia",
    userName: "LOREMS",
    created: "2h ago",
    marketCap: 10000,
    replies: 77,
    text: "Lorem ipsum dolor lalala sit amet noto",
  },
  {
    slug: "faposjflaksjdlf98932rjasjfkd5",
    imgUrl: "https://picsum.photos/128/128",
    name: "Lorem Ipsum Dolor Sit Amet",
    ticker: "LisDia",
    userName: "LOREMS",
    created: "2h ago",
    marketCap: 10000,
    replies: 77,
    text: "Lorem ipsum dolor lalala sit amet noto",
  },
  {
    slug: "faposjflaksjdlf98932rjasjfkd6",
    imgUrl: "https://picsum.photos/128/128",
    name: "Lorem Ipsum Dolor Sit Amet",
    ticker: "LisDia",
    userName: "LOREMS",
    created: "2h ago",
    marketCap: 10000,
    replies: 77,
    text: "Lorem ipsum dolor lalala sit amet noto",
  },
  {
    slug: "faposjflaksjdlf98932rjasjfkd7",
    imgUrl: "https://picsum.photos/128/128",
    name: "Lorem Ipsum Dolor Sit Amet",
    ticker: "LisDia",
    userName: "LOREMS",
    created: "2h ago",
    marketCap: 10000,
    replies: 77,
    text: "Lorem ipsum dolor lalala sit amet noto",
  },
  {
    slug: "faposjflaksjdlf98932rjasjfkd8",
    imgUrl: "https://picsum.photos/128/128",
    name: "Lorem Ipsum Dolor Sit Amet",
    ticker: "LisDia",
    userName: "LOREMS",
    created: "2h ago",
    marketCap: 10000,
    replies: 77,
    text: "Lorem ipsum dolor lalala sit amet noto",
  },
  {
    slug: "faposjflaksjdlf98932rjasjfkd9",
    imgUrl: "https://picsum.photos/128/128",
    name: "Lorem Ipsum Dolor Sit Amet",
    ticker: "LisDia",
    userName: "LOREMS",
    created: "2h ago",
    marketCap: 10000,
    replies: 77,
    text: "Lorem ipsum dolor lalala sit amet noto",
  },
  {
    slug: "faposjflaksjdlf98932rjasjfkd10",
    imgUrl: "https://picsum.photos/128/128",
    name: "Lorem Ipsum Dolor Sit Amet",
    ticker: "LisDia",
    userName: "LOREMS",
    created: "2h ago",
    marketCap: 10000,
    replies: 77,
    text: "Lorem ipsum dolor lalala sit amet noto",
  },
  {
    slug: "faposjflaksjdlf98932rjasjfkd11",
    imgUrl: "https://picsum.photos/128/128",
    name: "Lorem Ipsum Dolor Sit Amet",
    ticker: "LisDia",
    userName: "LOREMS",
    created: "2h ago",
    marketCap: 10000,
    replies: 77,
    text: "Lorem ipsum dolor lalala sit amet noto",
  },
  {
    slug: "faposjflaksjdlf98932rjasjfkd12",
    imgUrl: "https://picsum.photos/128/128",
    name: "Lorem Ipsum Dolor Sit Amet",
    ticker: "LisDia",
    userName: "LOREMS",
    created: "2h ago",
    marketCap: 10000,
    replies: 77,
    text: "Lorem ipsum dolor lalala sit amet noto",
  },
];
