export const TAB_ITEMS = [
  {
    id: "following",
    title: "Following",
  },
  {
    id: "terminal",
    title: "Terminal",
  },
];
export const DEFAULT_TAB = TAB_ITEMS[1].id;
export const DUMMY_ITEMS = [
  {
    slug: "faposjflaksjdlf98932rjasjfkd1",
    imgUrl: "https://picsum.photos/128/128",
    name: "Lorem Ipsum Dolor Sit Amet",
    ticker: "LisDia",
    userName: "LOREMS",
    created: "2h ago",
    marketCap: 10000,
    replies: 77,
    text: "Lorem ipsum dolor lalala sit amet noto",
  },
  {
    slug: "faposjflaksjdlf98932rjasjfkd2",
    imgUrl: "https://picsum.photos/128/128",
    name: "Lorem Ipsum Dolor Sit Amet",
    ticker: "LisDia",
    userName: "LOREMS",
    created: "2h ago",
    marketCap: 10000,
    replies: 77,
    text: "",
  },
  {
    slug: "faposjflaksjdlf98932rjasjfkd3",
    imgUrl: "https://picsum.photos/128/128",
    name: "Lorem Ipsum Dolor Sit Amet",
    ticker: "LisDia",
    userName: "LOREMS",
    created: "2h ago",
    marketCap: 10000,
    replies: 77,
    text: "Fusce ac dignissim erat. Morbi tristique dolor nec rhoncus dignissim. Vestibulum consectetur placerat quam ac laoreet. Fusce dictum ut massa vel molestie. Curabitur ac mauris sed augue molestie dapibus in in nisl.",
  },
  {
    slug: "faposjflaksjdlf98932rjasjfkd4",
    imgUrl: "https://picsum.photos/128/128",
    name: "Lorem Ipsum Dolor Sit Amet",
    ticker: "LisDia",
    userName: "LOREMS",
    created: "2h ago",
    marketCap: 10000,
    replies: 77,
    text: "Lorem ipsum dolor lalala sit amet noto",
  },
  {
    slug: "faposjflaksjdlf98932rjasjfkd5",
    imgUrl: "https://picsum.photos/128/128",
    name: "Lorem Ipsum Dolor Sit Amet",
    ticker: "LisDia",
    userName: "LOREMS",
    created: "2h ago",
    marketCap: 10000,
    replies: 77,
    text: "Lorem ipsum dolor lalala sit amet noto",
  },
  {
    slug: "faposjflaksjdlf98932rjasjfkd6",
    imgUrl: "https://picsum.photos/128/128",
    name: "Lorem Ipsum Dolor Sit Amet",
    ticker: "LisDia",
    userName: "LOREMS",
    created: "2h ago",
    marketCap: 10000,
    replies: 77,
    text: "Lorem ipsum dolor lalala sit amet noto",
  },
  {
    slug: "faposjflaksjdlf98932rjasjfkd7",
    imgUrl: "https://picsum.photos/128/128",
    name: "Lorem Ipsum Dolor Sit Amet",
    ticker: "LisDia",
    userName: "LOREMS",
    created: "2h ago",
    marketCap: 10000,
    replies: 77,
    text: "Maecenas mollis ac turpis et finibus. Nunc et magna egestas nisl imperdiet porttitor eu eu mauris. Vivamus sit amet dui at felis egestas accumsan nec sed nisi. Aenean non convallis ex. Etiam in massa at sapien scelerisque consequat. Cras finibus, ante id lobortis finibus, leo odio gravida metus, sed faucibus lacus nisi non nunc. Curabitur ligula leo, consectetur sit amet facilisis id, maximus ut eros. Morbi lobortis, mi feugiat dapibus aliquet, nunc enim mattis erat, eget ultricies leo ligula rhoncus metus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },
  {
    slug: "faposjflaksjdlf98932rjasjfkd8",
    imgUrl: "https://picsum.photos/128/128",
    name: "Lorem Ipsum Dolor Sit Amet",
    ticker: "LisDia",
    userName: "LOREMS",
    created: "2h ago",
    marketCap: 10000,
    replies: 77,
    text: "Lorem ipsum dolor lalala sit amet noto",
  },
  {
    slug: "faposjflaksjdlf98932rjasjfkd9",
    imgUrl: "https://picsum.photos/128/128",
    name: "Lorem Ipsum Dolor Sit Amet",
    ticker: "LisDia",
    userName: "LOREMS",
    created: "2h ago",
    marketCap: 10000,
    replies: 77,
    text: "Lorem ipsum dolor lalala sit amet noto",
  },
  {
    slug: "faposjflaksjdlf98932rjasjfkd10",
    imgUrl: "https://picsum.photos/128/128",
    name: "Lorem Ipsum Dolor Sit Amet",
    ticker: "LisDia",
    userName: "LOREMS",
    created: "2h ago",
    marketCap: 10000,
    replies: 77,
    text: "Lorem ipsum dolor lalala sit amet noto",
  },
  {
    slug: "faposjflaksjdlf98932rjasjfkd11",
    imgUrl: "https://picsum.photos/128/128",
    name: "Lorem Ipsum Dolor Sit Amet",
    ticker: "LisDia",
    userName: "LOREMS",
    created: "2h ago",
    marketCap: 10000,
    replies: 77,
    text: "Lorem ipsum dolor lalala sit amet noto",
  },
  {
    slug: "faposjflaksjdlf98932rjasjfkd12",
    imgUrl: "https://picsum.photos/128/128",
    name: "Lorem Ipsum Dolor Sit Amet",
    ticker: "LisDia",
    userName: "LOREMS",
    created: "2h ago",
    marketCap: 10000,
    replies: 77,
    text: "Lorem ipsum dolor lalala sit amet noto",
  },
];
